(() => {
  'use strict';
  const root = document.getElementById('app');
  const notice = document.getElementById('notice');
  const music = document.getElementById('birthday-music');
  const musicButton = document.getElementById('music-toggle');
  const KEY = 'caicai-birthday-v1';
  const state = {stage:'intro',profile:null,answers:Array(9).fill(null),chapter:0,wishCompleted:false,candleCompleted:false,completedAt:null};
  let storageAvailable = true;
  try { const saved = JSON.parse(localStorage.getItem(KEY) || 'null'); if (saved && saved.profile && typeof saved.profile.name === 'string' && Number.isInteger(saved.profile.age) && saved.profile.age>=1 && saved.profile.age<=99 && saved.profile.zodiac) {
    state.profile = saved.profile; state.answers = Array.isArray(saved.answers) ? Array.from({length:9},(_,i)=>saved.answers[i] ?? null) : state.answers;
    state.chapter = Math.min(2,Math.max(0,Number(saved.chapter)||0)); state.wishCompleted=!!saved.wishCompleted;
    state.candleCompleted=!!saved.candleCompleted;state.completedAt=saved.completedAt||null;
    state.stage = saved.stage || 'moments';
  }} catch {storageAvailable=false;}
  function save(){try{localStorage.setItem(KEY,JSON.stringify({profile:state.profile,answers:state.answers,chapter:state.chapter,stage:state.stage,wishCompleted:state.wishCompleted,candleCompleted:state.candleCompleted,completedAt:state.completedAt}));}catch{storageAvailable=false;}}
  function msg(value){ notice.textContent=value; notice.classList.add('visible'); clearTimeout(msg.timer);msg.timer=setTimeout(()=>notice.classList.remove('visible'),3800); }
  function escape(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function zodiac(m,d){const thresholds=[[1,20,'水瓶座','♒'],[2,19,'雙魚座','♓'],[3,21,'牡羊座','♈'],[4,20,'金牛座','♉'],[5,21,'雙子座','♊'],[6,22,'巨蟹座','♋'],[7,23,'獅子座','♌'],[8,23,'處女座','♍'],[9,23,'天秤座','♎'],[10,24,'天蠍座','♏'],[11,23,'射手座','♐'],[12,22,'摩羯座','♑']];let found=thresholds.at(-1);for(const item of thresholds){if(m>item[0]||(m===item[0]&&d>=item[1])) found=item;}return {name:found[2],symbol:found[3]};}
  function setStage(stage){if(state.stage==='candle'&&stage!=='candle')stopMicrophone();const leavingVideo=['morning','cake','birthday','song'].includes(state.stage),old=leavingVideo?root.querySelector('#scene-video'):null;state.stage=stage;save();render();window.scrollTo(0,0);if(old)try{old.pause();old.removeAttribute('src');}catch{}if(leavingVideo&&musicOn&&!['morning','cake','birthday','song'].includes(stage))music.play().catch(()=>{});}
  function renderIntro(){root.innerHTML=`<section class="panel intro welcome-panel"><div class="welcome-sparkles" aria-hidden="true"><i>✦</i><i>✿</i><i>✧</i><i>✿</i><i>✦</i><i>✧</i></div><div class="eyebrow">一個人也可以好好過生日</div><div class="opening-mark" aria-hidden="true">🎁</div><p class="welcome-first">今天，有一份特別的驚喜，留給你。</p><h1 class="welcome-next">在生日開始之前，讓我們先認識你一點。</h1><p class="lead">今天的故事，從你開始。</p><button class="primary" type="button" data-action="start">☀️ 開始我的生日</button></section>`;}
  function renderProfile(){root.innerHTML=`<section class="panel form"><div class="eyebrow">在生日開始以前</div><h1>今天，先認識你一點</h1><p class="lead">只需要一些小小的資料。</p><form id="profile-form" novalidate><div class="field"><label for="name">想讓我們怎麼稱呼你？</label><input id="name" name="name" autocomplete="nickname" maxlength="12" placeholder="稱呼／暱稱" required><span class="small-note">約 6 個中文字以內</span></div><div class="field"><fieldset><legend>選擇你的生日版本</legend><div class="choice-row"><button type="button" class="choice" data-version="female" aria-pressed="true">女生版</button><button type="button" class="choice" data-version="male" aria-pressed="false">男生版</button></div></fieldset></div><div class="field"><label for="month">生日（月／日）</label><div class="date-row"><select id="month" name="month" aria-label="生日月份"><option value="">月份</option>${Array.from({length:12},(_,i)=>`<option value="${i+1}">${i+1} 月</option>`).join('')}</select><select id="day" name="day" aria-label="生日日期"><option value="">日期</option></select></div></div><div class="field"><label for="age">今年幾歲？</label><input id="age" type="number" inputmode="numeric" min="1" max="99" name="age" placeholder="1～99 歲" required></div><p id="form-error" class="error" role="alert"></p><button class="primary" type="submit" style="width:100%">🎁 開啟我的生日驚喜</button></form></section>`;root.dataset.version='female';}
  function render(){try{document.body.classList.toggle('male',state.profile?.version==='male');document.body.classList.toggle('immersive-video',state.stage==='morning'||state.stage==='cake');document.body.dataset.chapter=String(state.chapter);root.style.zIndex=state.stage==='morning'||state.stage==='cake'?'40':'';if(state.stage==='profile')renderProfile();else if(state.stage==='intro')renderIntro();else renderLater();}catch{root.innerHTML=`<section class="panel"><h1>這一頁稍微停了一下。</h1><p class="lead">你的生日進度還在，可以回到小片刻繼續。</p><button class="primary" data-action="recover" type="button">繼續我的生日</button></section>`;}}
  const chapters=[{title:'☀️ 早晨｜今天的我',short:'早晨'},{title:'🌤️ 午後｜好好對待自己',short:'午後'},{title:'🌙 夜晚｜留給自己的話',short:'夜晚'}];
  const moments=[
    {title:'此刻的心情',question:'今天醒來，你的心情比較靠近哪一種？',options:['輕輕期待','有點平靜','說不上來','想慢慢來']},
    {title:'對自己說一句話',question:'如果可以對今天的自己說一句話，你想說什麼？'},
    {title:'留一點期待',question:'今天想留給自己哪一種小小的期待？',options:['吃一樣喜歡的東西','聽一首歌','安靜休息','讓今天自然發生']},
    {title:'一點好好對待',question:'現在，想用什麼方式對自己好一點？',options:['喝杯喜歡的飲料','到外面走走','放下手機休息','照自己的步調過']},
    {title:'停一下',question:'慢慢吸氣，再緩緩吐氣。這一刻，想把什麼留給自己？'},
    {title:'看見自己',question:'最近的自己，有哪件小事值得被看見？'},
    {title:'今天的一點光',question:'今天有哪個小片刻，想留下來記得？'},
    {title:'輕輕放下',question:'有什麼事情，今晚想先暫時放下？',options:['對自己的苛求','還沒做完的事','別人的期待','現在先不決定']},
    {title:'給新的一歲',question:'送給新的一歲一句話吧。'}
  ];
  let currentMoment=0,nightAcknowledged=false,mediaStream=null,audioContext=null,frame=null,holdTimer=null,holdStarted=0,holdType=null,candleAnimating=false,photoUrl=null,photoImage=null;
  function currentGreeting(){const h=new Date().getHours();return h<11?'早安':h<17?'午安':'晚安';}
  function suggestedChapter(){const h=new Date().getHours();return h<12?0:h<18?1:2;}
  function renderLater(){switch(state.stage){case 'morning':return renderMorningVideo();case 'cake':case 'birthday':case 'song':return renderVideo(state.stage);case 'moments':return renderMoments();case 'wish':return renderWish();case 'candle':return renderCandle();case 'card':return renderCard();default:state.stage='moments';save();return renderMoments();}}
  const videoScenes={morning:{title:'今天，是你的生日。',subtitle:'新的一歲，從這個早晨開始。',eyebrow:'生日早晨',label:'生日早晨影片',hint:'第一人稱的生日早晨。',next:'跳過影片',action:'skip-morning'},cake:{title:'祝你生日快樂。',subtitle:'有人把祝福送到了。',eyebrow:'一份送到的祝福',label:'蔡蔡送蛋糕影片',hint:'有人把祝福送到，然後把生日還給你。',next:'繼續生日',action:'skip-cake'},birthday:{title:'這個生日，完整地屬於你。',subtitle:'收下這份正式的生日祝福。',eyebrow:'生日的祝福',label:'生日正式影片',hint:'看完以後，留一個願望給自己。',next:'繼續許願',action:'skip-birthday'},song:{title:'生日快樂。',subtitle:'這首歌，唱給今天的你。',eyebrow:'生日快樂歌',label:'生日快樂歌影片',hint:'唱完以後，把今天好好收藏。',next:'看看我的生日紀念',action:'skip-song'}};
  function renderVideo(kind){
    const scene=videoScenes[kind];
    root.innerHTML=`<section class="panel video-panel ${kind==='cake'?'cake-video-panel':''}"><div class="eyebrow">${scene.eyebrow}</div><h1>${scene.title}</h1><p class="lead">${scene.subtitle}</p><div class="video-frame"><video id="scene-video" playsinline webkit-playsinline preload="none" ${kind==='cake'?'':'poster="cake-still.jpg"'} aria-label="${scene.label}"></video>${kind==='cake'?'<img class="cake-still-end" src="cake-still.jpg" alt="桌上的生日蛋糕" onerror="this.hidden=true">':''}</div><p id="video-status" class="small-note">${scene.hint}</p><div class="actions"><button class="primary" data-action="play-video" type="button">▶ 播放影片</button><button class="text-button" data-action="${scene.action}" type="button">${scene.next}</button></div></section>`;
    const video=root.querySelector('#scene-video');
    video.src=({cake:'cake-delivery-song.mp4',birthday:'birthday-final.mp4',song:'birthday-song.mp4'})[kind];
    video.addEventListener('timeupdate',()=>{if(kind==='cake'&&state.stage==='cake'&&video.currentTime>=16)root.querySelector('.cake-still-end')?.classList.add('visible');});
    video.addEventListener('ended',()=>{if(state.stage!==kind)return;const status=root.querySelector('#video-status');if(kind==='cake'){root.querySelector('.cake-still-end')?.classList.add('visible');status.textContent='蛋糕留下來了。這個生日，完整地屬於你。';}else status.textContent='影片已結束，準備好了就繼續。';});
    video.addEventListener('error',()=>{if(state.stage!==kind)return;const status=root.querySelector('#video-status');if(!status)return;if(kind==='cake'&&!video.dataset.fallback){video.dataset.fallback='1';video.src='cake-delivery.mp4';status.textContent='歌曲版本暫時無法播放，可再點播放或直接繼續。';return;}status.textContent='影片暫時無法播放，你仍可以繼續。';});
  }
  function renderMorningVideo(){
    root.innerHTML=`<section class="panel video-panel morning-video-panel"><div class="eyebrow">生日早晨</div><h1>今天，是你的生日。</h1><p class="lead">新的一歲，從這個早晨開始。</p><div class="video-frame"><video id="scene-video" playsinline webkit-playsinline preload="metadata" aria-label="生日早晨影片"></video><div class="morning-finale" hidden>今天的故事，從這裡開始 ✨</div></div><p id="video-status" class="small-note">第一人稱的生日早晨。</p><div class="actions"><button class="primary" id="morning-play" type="button">▶ 播放影片</button><button class="primary" id="morning-continue" type="button" hidden>☀️ 開始今天的故事</button><button class="text-button" id="morning-skip" type="button">跳過影片</button></div></section>`;
    const video=root.querySelector('#scene-video');
    const playButton=root.querySelector('#morning-play');
    const continueButton=root.querySelector('#morning-continue');
    const skipButton=root.querySelector('#morning-skip');
    const status=root.querySelector('#video-status');
    function unavailable(){if(state.stage==='morning')status.textContent='影片暫時無法播放，你仍可以繼續。';}
    function skip(){
      if(state.stage!=='morning')return;
      state.stage='moments';save();render();window.scrollTo(0,0);
      try{video.pause();}catch{}
      if(musicOn)music.play().catch(()=>{});
    }
    playButton.addEventListener('click',()=>{
      if(state.stage!=='morning')return;
      music.pause();
      try{
        const started=video.play();
        if(started?.then)started.then(()=>{if(state.stage==='morning')playButton.textContent='影片播放中';},unavailable);
      }catch{unavailable();}
    });
    skipButton.addEventListener('click',skip);
    continueButton.addEventListener('click',skip);
    video.addEventListener('ended',()=>{if(state.stage!=='morning')return;playButton.hidden=true;continueButton.hidden=false;root.querySelector('.morning-finale').hidden=false;status.textContent='這一刻，慢慢留在心裡。準備好了再繼續。';});
    video.addEventListener('error',unavailable);
    video.src=state.profile.version==='male'?'morning-male.mp4':'morning-female.mp4';
  }
  function firstUnanswered(ch){const start=ch*3;for(let i=start;i<start+3;i++)if(state.answers[i]===null)return i;return start;}
  function renderMoments(){document.body.dataset.chapter=String(state.chapter);const done=state.answers.filter(x=>x!==null).length;if(currentMoment<state.chapter*3||currentMoment>=state.chapter*3+3)currentMoment=firstUnanswered(state.chapter);let note='';if(state.chapter===2&&new Date().getHours()<18&&!nightAcknowledged){root.innerHTML=`<section class="panel"><div class="eyebrow">🌙 夜晚｜留給自己的話</div><h1>現在還沒到夜晚。</h1><p class="lead">如果你想晚一點再回來，我們會把這裡留給你。</p><div class="actions"><button class="primary" data-action="night-continue">現在就繼續</button><button class="secondary" data-chapter="0">回到早晨</button></div></section>`;return;}if(done===9)note='<p class="small-note">九個小片刻，都已經留在今天了。</p>';
    const m=moments[currentMoment],answer=state.answers[currentMoment];root.innerHTML=`<section class="panel moments-panel"><div class="eyebrow">${escape(state.profile.name)}，${currentGreeting()}。今天按你的步調來。</div><h1>生日的一天</h1><p class="small-note">已留下 ${done}／9 個小片刻 · 現在推薦 ${chapters[suggestedChapter()].short}</p><nav class="chapter-nav" aria-label="選擇章節">${chapters.map((c,i)=>`<button type="button" class="chapter-button" data-chapter="${i}" aria-current="${i===state.chapter?'true':'false'}">${c.title}</button>`).join('')}</nav><div class="moment-nav" aria-label="本章小片刻">${[0,1,2].map(n=>{let idx=state.chapter*3+n;return `<button type="button" data-moment="${idx}" aria-current="${currentMoment===idx?'true':'false'}" aria-label="第 ${idx+1} 個小片刻${state.answers[idx]!==null?'，已留下':''}">${state.answers[idx]!==null?'✦':idx+1}</button>`}).join('')}</div><div class="moment-body"><span class="moment-number">小片刻 ${currentMoment+1}／9</span><h2>${m.title}</h2><p>${m.question}</p>${m.options?`<div class="options">${m.options.map(o=>`<button type="button" class="choice" data-answer="${escape(o)}" aria-pressed="${answer===o?'true':'false'}">${escape(o)}</button>`).join('')}</div>`:`<label class="sr-only" for="moment-text">你的回答</label><textarea id="moment-text" maxlength="280" placeholder="慢慢寫，寫多少都好。">${escape(answer||'')}</textarea><button class="primary" type="button" data-action="save-text">留下這句話</button>`}</div>${note}<div class="actions">${done===9?'<button class="primary" type="button" data-action="to-cake">🎁 接受今天為你準備的驚喜</button>':'<button class="secondary" type="button" data-action="next-moment">看看下一個小片刻</button>'}</div></section>`;}
  function recordAnswer(value){state.answers[currentMoment]=value;save();const next=state.answers.findIndex((x,i)=>i>currentMoment&&x===null);if(next>=0){state.chapter=Math.floor(next/3);currentMoment=next;}else{const first=state.answers.findIndex(x=>x===null);if(first>=0){state.chapter=Math.floor(first/3);currentMoment=first;}}save();renderMoments();}
  function renderWish(){root.innerHTML=`<section class="panel ritual-panel"><div class="eyebrow">留一個願望給自己</div><div class="cake-scene ${state.wishCompleted?'dim':''}"><img src="cake-still.jpg" alt="留在桌上的生日蛋糕" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="scene-fallback" hidden>🎂</div></div>${state.wishCompleted?'<h1>願望收好了。</h1><p class="lead">現在，把蠟燭吹熄吧。</p><button class="primary" data-action="to-candle">去吹蠟燭</button>':`<h1>閉上眼睛，在心裡許個願。</h1><p class="lead">不用說出來，也不用寫下來。<br>準備好了，再輕輕按下。</p><button class="hold-button" type="button" data-hold="wish" aria-label="長按我許好了約一點四秒"><span class="hold-ring"></span><span>✨ 我許好了 ✨</span></button><p class="small-note">長按直到光圈完成 ✨</p>`}</section>`;if(!state.wishCompleted)requestAnimationFrame(()=>requestAnimationFrame(()=>root.querySelector('.cake-scene')?.classList.add('dim')));}
  function candleMarkup(){return String(state.profile.age).split('').map(digit=>`<span class="candle-slot"><img class="candle-img" src="candle_${digit}.png" alt="${digit} 字蠟燭" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="candle-fallback" hidden>${digit}</span><span class="candle-flame" aria-hidden="true"></span></span>`).join('');}
  function renderCandle(){root.innerHTML=`<section class="panel ritual-panel"><div class="eyebrow">生日的燭光</div><div class="cake-scene ${state.candleCompleted?'':'dim'}"><img src="cake-still.jpg" alt="桌上的生日蛋糕" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="scene-fallback" hidden>🎂</div><div class="candles ${state.candleCompleted?'extinguished':''}" aria-label="${state.profile.age} 歲生日蠟燭">${candleMarkup()}</div></div>${state.candleCompleted?'<h1>新的一歲，亮起來了。</h1><p class="lead">今天的光，留給你自己。</p><button class="primary" data-action="to-card">看看我的生日紀念</button>':`<h1>輕輕吹熄蠟燭</h1><p class="small-note">可以對著麥克風吹氣，也可以長按吹熄。<br>聲音只在這台裝置即時判斷，不會錄音或上傳。</p><div class="actions"><button class="secondary" type="button" data-action="mic">使用麥克風吹氣</button><button class="hold-button" type="button" data-hold="candle" aria-label="長按吹熄蠟燭約一點四秒"><span class="hold-ring"></span><span>長按這裡吹熄蠟燭</span></button></div><p id="mic-status" class="small-note" role="status"></p>`}</section>`;}
  function blowOut(){if(candleAnimating||state.candleCompleted)return;candleAnimating=true;stopMicrophone();const hold=root.querySelector('[data-hold]');if(hold)hold.disabled=true;root.querySelector('.candles')?.classList.add('extinguished');root.querySelector('.cake-scene')?.classList.remove('dim');setTimeout(()=>{state.candleCompleted=true;candleAnimating=false;save();if(state.stage==='candle'&&state.profile)renderCandle();},800);}
  async function useMicrophone(){const status=root.querySelector('#mic-status');if(!status)return;status.textContent='正在聆聽吹氣聲……';if(!navigator.mediaDevices?.getUserMedia){status.textContent='這個瀏覽器無法使用麥克風，請改用長按。';return;}try{mediaStream=await navigator.mediaDevices.getUserMedia({audio:true});const Context=window.AudioContext||window.webkitAudioContext;if(!Context)throw Error('audio context unsupported');audioContext=new Context();await audioContext.resume();const source=audioContext.createMediaStreamSource(mediaStream);const analyser=audioContext.createAnalyser();analyser.fftSize=1024;source.connect(analyser);const samples=new Uint8Array(analyser.fftSize);let baseline=.015,overSince=0;status.textContent='準備好了，對著麥克風吹氣吧。也可以改用長按。';const sample=()=>{if(!mediaStream||state.stage!=='candle'||state.candleCompleted)return;analyser.getByteTimeDomainData(samples);let sum=0;for(const v of samples)sum+=((v-128)/128)**2;const level=Math.sqrt(sum/samples.length);baseline=baseline*.985+Math.min(level,.08)*.015;const active=level>Math.max(.075,baseline*2.7);if(active){if(!overSince)overSince=performance.now();if(performance.now()-overSince>320){blowOut();return;}}else overSince=0;frame=requestAnimationFrame(sample);};sample();}catch{stopMicrophone();status.textContent='麥克風暫時無法使用，請長按吹熄蠟燭。';}}
  function stopMicrophone(){if(frame)cancelAnimationFrame(frame);frame=null;mediaStream?.getTracks().forEach(t=>t.stop());mediaStream=null;if(audioContext){audioContext.close().catch(()=>{});audioContext=null;}}
  function renderCard(){const p=state.profile,date=state.completedAt?new Date(state.completedAt):new Date();const formatted=new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'long',day:'numeric'}).format(date);root.innerHTML=`<section class="panel card-panel"><div class="eyebrow">把今天留給自己</div><h1>我的生日紀念</h1><div id="memory-card" class="memory-card"><div class="card-ornament">✦ &nbsp; ✦ &nbsp; ✦</div><div class="card-photo" ${photoUrl?'':'hidden'}><img src="${photoUrl||''}" alt="選用的紀念照片"></div><div class="card-greeting">親愛的 ${escape(p.name)}</div><div class="card-age">${p.age} 歲，生日快樂</div><div class="card-meta">${p.month} 月 ${p.day} 日　·　${escape(p.zodiac.name)} ${escape(p.zodiac.symbol)}</div><p>今年，我也為自己許了一個願。</p><p>原來一個人，也可以好好過生日。</p>${[1,5,8].filter(i=>state.answers[i]).map(i=>`<div class="card-answer">${escape(state.answers[i])}</div>`).join('')}<div class="card-date">${escape(formatted)}</div></div><div class="photo-controls"><label class="secondary upload-label" for="photo">選一張自己的照片<input id="photo" type="file" accept="image/*" hidden></label><button class="text-button" data-action="remove-photo" type="button">不放照片</button></div><p class="small-note">照片只用於這次紀念卡，不會上傳或儲存。重新開啟網站後需重新選取。</p><div class="actions"><button class="primary" data-action="download-card" type="button">下載紀念卡圖片</button></div></section>`;}
  function startSceneVideo(){const video=root.querySelector('#scene-video');if(!video)return;music.pause();try{const started=video.play();if(started?.then)started.then(()=>{const button=root.querySelector('[data-action="play-video"]');if(button)button.textContent='影片播放中';},()=>{const status=root.querySelector('#video-status');if(status)status.textContent='影片無法播放，請再點一次，或直接繼續。';});}catch{const status=root.querySelector('#video-status');if(status)status.textContent='影片無法播放，請再點一次，或直接繼續。';}}
  root.addEventListener('click',e=>{const version=e.target.closest('button[data-version]');if(version){root.dataset.version=version.dataset.version;root.querySelectorAll('[data-version]').forEach(b=>b.setAttribute('aria-pressed',String(b===version)));return;}const chapter=e.target.closest('button[data-chapter]');if(chapter){state.chapter=Number(chapter.dataset.chapter);currentMoment=firstUnanswered(state.chapter);save();renderMoments();return;}const moment=e.target.closest('[data-moment]');if(moment){currentMoment=Number(moment.dataset.moment);renderMoments();return;}const answer=e.target.closest('[data-answer]');if(answer){recordAnswer(answer.dataset.answer);return;}const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;switch(action){case 'start':activateMusic();setStage('profile');break;case 'recover':setStage(state.profile?'moments':'intro');break;case 'play-video':startSceneVideo();break;case 'skip-morning':setStage('moments');break;case 'skip-cake':setStage('birthday');break;case 'skip-birthday':setStage('wish');break;case 'skip-song':if(!state.completedAt)state.completedAt=new Date().toISOString();setStage('card');break;case 'night-continue':nightAcknowledged=true;renderMoments();break;case 'next-moment':{const next=state.answers.findIndex((a,i)=>i>currentMoment&&a===null);const first=state.answers.findIndex(a=>a===null);currentMoment=next>=0?next:first>=0?first:(currentMoment+1)%9;state.chapter=Math.floor(currentMoment/3);save();renderMoments();break;}case 'save-text':{const value=root.querySelector('#moment-text').value.trim();if(!value){msg('可以慢慢想；寫下一點點就好。');return;}recordAnswer(value);break;}case 'to-cake':setStage('cake');startSceneVideo();break;case 'to-candle':setStage('candle');break;case 'mic':useMicrophone();break;case 'to-song':setStage('song');break;case 'remove-photo':if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=null;photoImage=null;renderCard();break;case 'download-card':downloadCard();break;}});
  root.addEventListener('change',e=>{if(e.target.id==='photo'){const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){msg('請選擇圖片檔。');return;}if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=URL.createObjectURL(file);photoImage=new Image();photoImage.onload=()=>renderCard();photoImage.onerror=()=>{URL.revokeObjectURL(photoUrl);photoUrl=null;photoImage=null;msg('這張照片暫時無法顯示，可以選其他照片。');};photoImage.src=photoUrl;}});
  function clearHold(){clearTimeout(holdTimer);holdTimer=null;holdType=null;root.querySelectorAll('.holding').forEach(el=>el.classList.remove('holding'));}
  root.addEventListener('pointerdown',e=>{const button=e.target.closest('[data-hold]');if(!button||button.disabled)return;e.preventDefault();clearHold();button.classList.add('holding');holdType=button.dataset.hold;holdStarted=performance.now();try{button.setPointerCapture(e.pointerId);}catch{}holdTimer=setTimeout(()=>{const type=holdType;clearHold();navigator.vibrate?.(35);if(type==='wish'){state.wishCompleted=true;save();renderWish();}else if(type==='candle')blowOut();},1400);});
  root.addEventListener('pointerup',clearHold);root.addEventListener('pointercancel',clearHold);window.addEventListener('blur',clearHold);
  root.addEventListener('keydown',e=>{const b=e.target.closest('[data-hold]');if(b&&(e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();if(holdTimer)return;b.classList.add('holding');holdType=b.dataset.hold;holdTimer=setTimeout(()=>{const t=holdType;clearHold();if(t==='wish'){state.wishCompleted=true;save();renderWish();}else blowOut();},1400);}});root.addEventListener('keyup',e=>{if(e.key===' '||e.key==='Enter')clearHold();});
  document.addEventListener('visibilitychange',()=>{if(document.hidden)stopMicrophone();});
  function rounded(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();}
  function wrap(ctx,text,maxWidth,maxLines=3){const lines=[];let line='';for(const char of Array.from(text)){if(ctx.measureText(line+char).width>maxWidth&&line){lines.push(line);line=char;if(lines.length>=maxLines)break;}else line+=char;}if(line&&lines.length<maxLines)lines.push(line);return lines;}
  async function downloadCard(){const button=root.querySelector('[data-action="download-card"]');if(button)button.disabled=true;try{const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const c=canvas.getContext('2d');if(!c)throw Error('canvas');const grad=c.createLinearGradient(0,0,1080,1350);grad.addColorStop(0,state.profile.version==='male'?'#e8efe9':'#fff7ed');grad.addColorStop(1,state.profile.version==='male'?'#d7e4df':'#f0e1d4');c.fillStyle=grad;c.fillRect(0,0,1080,1350);c.fillStyle='#fffdf8';rounded(c,62,58,956,1234,38);c.fill();c.strokeStyle=state.profile.version==='male'?'#a0b9ad':'#d7b894';c.lineWidth=3;rounded(c,86,82,908,1186,26);c.stroke();c.textAlign='center';c.fillStyle='#b59060';c.font='34px serif';c.fillText('✦   ✦   ✦',540,165);let y=244;if(photoImage?.complete&&photoImage.naturalWidth){const size=210;const x=435,top=190;c.save();rounded(c,x,top,size,size,105);c.clip();const s=Math.max(size/photoImage.naturalWidth,size/photoImage.naturalHeight),w=photoImage.naturalWidth*s,h=photoImage.naturalHeight*s;c.drawImage(photoImage,x+(size-w)/2,top+(size-h)/2,w,h);c.restore();y=462;}c.fillStyle='#594438';c.font='bold 54px serif';c.fillText(`親愛的 ${state.profile.name}`,540,y);c.font='bold 70px serif';c.fillText(`${state.profile.age} 歲，生日快樂`,540,y+105);c.fillStyle='#967661';c.font='34px serif';c.fillText(`${state.profile.month} 月 ${state.profile.day} 日   ·   ${state.profile.zodiac.name} ${state.profile.zodiac.symbol}`,540,y+175);c.strokeStyle='#d8c3a6';c.beginPath();c.moveTo(270,y+230);c.lineTo(810,y+230);c.stroke();c.fillStyle='#594438';c.font='39px serif';c.fillText('今年，我也為自己許了一個願。',540,y+310);c.fillText('原來一個人，也可以好好過生日。',540,y+373);const answers=[1,5,8].map(i=>state.answers[i]).filter(Boolean);let answerY=y+460;c.fillStyle='#806c5c';c.font='32px serif';for(const answer of answers.slice(0,2)){for(const line of wrap(c,answer,710,2)){c.fillText(line,540,answerY);answerY+=45;}answerY+=25;}c.fillStyle='#a48a70';c.font='30px serif';c.fillText(new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'long',day:'numeric'}).format(new Date(state.completedAt||Date.now())),540,1200);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('export');const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${state.profile.name}-生日紀念卡.png`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch{msg('圖片下載暫時無法使用。紀念卡仍在畫面上，可以先截圖保存。');}finally{if(button)button.disabled=false;}}
  root.addEventListener('change',e=>{if(e.target.id==='month'){const m=Number(e.target.value);const day=root.querySelector('#day');day.innerHTML='<option value="">日期</option>'+Array.from({length:m?new Date(2024,m,0).getDate():0},(_,i)=>`<option value="${i+1}">${i+1} 日</option>`).join('');}});
  root.addEventListener('submit',e=>{if(e.target.id!=='profile-form')return;e.preventDefault();const form=e.target;const name=form.elements.name.value.trim();const month=Number(form.elements.month.value);const day=Number(form.elements.day.value);const age=Number(form.elements.age.value);const error=root.querySelector('#form-error');if(!name||Array.from(name).length>12){error.textContent='請填寫稱呼（約 6 個中文字以內）。';return;}if(!month||!day||day>new Date(2024,month,0).getDate()){error.textContent='請選擇生日的月份與日期。';return;}if(!Number.isInteger(age)||age<1||age>99){error.textContent='請填寫 1～99 歲。';return;}state.profile={name,version:root.dataset.version||'female',month,day,age,zodiac:zodiac(month,day)};setStage('morning');if(!storageAvailable)msg('這個瀏覽器暫時無法儲存進度，關閉頁面後可能需要重新開始。');});
  let musicOn=false;async function activateMusic(){musicOn=true;musicButton.textContent='♫ 音樂開';musicButton.setAttribute('aria-pressed','true');musicButton.setAttribute('aria-label','關閉音樂');if(!music.getAttribute('src'))music.src='background-music.m4a';if(['morning','cake','birthday','song'].includes(state.stage))return;try{await music.play();}catch{musicOn=false;musicButton.textContent='♫ 音樂關';musicButton.setAttribute('aria-pressed','false');musicButton.setAttribute('aria-label','開啟音樂');}}
  musicButton.addEventListener('click',()=>{if(musicOn){musicOn=false;music.pause();musicButton.textContent='♫ 音樂關';musicButton.setAttribute('aria-pressed','false');musicButton.setAttribute('aria-label','開啟音樂');}else activateMusic();});
  root.addEventListener('click',e=>{if(!e.target.closest('[data-action="to-card"]')||state.stage!=='candle'||!state.candleCompleted)return;if(!state.completedAt)state.completedAt=new Date().toISOString();setStage('card');});
  render();
})();
